### ISSUE TITLE
Private variable naming convertions

### ISSUE THREAD

**Issue by PiJoules** [jmal0/sudoku#4]
Have each private variable end with _ (Sudoku\* puzz_)

**Comment by jmal0** [comment]
This is not a code review

**Comment by PiJoules** [comment]
Consistant variable naming: you spell each public variable as you do a private one. Having the trailing underscore makes more readable.

**Comment by jmal0** [comment]
I will take this into consideration

**Comment by PiJoules** [comment]
Be sure to close this issue when implemented.

**Comment by jmal0** [comment]
This is somewhat irrelevant because all my class variables are private. The only use would be differentiating class variables and function arguments. And in that case using this. would be more explicit. Also there is no standard c++ private variable naming convention like python has. Tell me what to do leo
